project:
  type: website
  output-dir: docs

website:
  title: "Rain Hartos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - MiniProject4/MiniProject4.qmd
      - projectlinks.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full